package dev.nucleusframework.nna.plugin.codegen

import dev.nucleusframework.nna.plugin.ir.KneEnum
import dev.nucleusframework.nna.plugin.ir.KneEnumEntry
import dev.nucleusframework.nna.plugin.ir.KneModule
import dev.nucleusframework.nna.plugin.ir.KneParam
import dev.nucleusframework.nna.plugin.ir.KneType
import org.junit.Assert.assertEquals
import org.junit.Test

class FfmProxyGeneratorEnumTest {

    @Test
    fun `generates simple enum entries`() {
        val source = generate(
            KneEnum(
                simpleName = "Operation",
                fqName = "demo.Operation",
                entries = listOf(
                    KneEnumEntry("ADD"),
                    KneEnumEntry("SUBTRACT"),
                    KneEnumEntry("MULTIPLY"),
                ),
            ),
        )

        assertEquals(
            """
            // Auto-generated by kotlin-native-export plugin. Do not modify.
            package demo

            enum class Operation {
                ADD,
                SUBTRACT,
                MULTIPLY;
            }

            """.trimIndent(),
            source,
        )
    }

    @Test
    fun `generates constructor enum entries with property values`() {
        val source = generate(
            KneEnum(
                simpleName = "HttpStatus",
                fqName = "demo.HttpStatus",
                entries = listOf(
                    KneEnumEntry("OK", listOf("200", "\"OK\"")),
                    KneEnumEntry("NOT_FOUND", listOf("404", "\"Not Found\"")),
                ),
                constructorParams = listOf(
                    KneParam("code", KneType.INT),
                    KneParam("label", KneType.STRING),
                ),
            ),
        )

        assertEquals(
            """
            // Auto-generated by kotlin-native-export plugin. Do not modify.
            package demo

            enum class HttpStatus(val code: Int, val label: String) {
                OK(200, "OK"),
                NOT_FOUND(404, "Not Found");
            }

            """.trimIndent(),
            source,
        )
    }

    @Test
    fun `empty entries still emit a valid enum class`() {
        val source = generate(KneEnum("Empty", "demo.Empty", emptyList()))
        assertEquals(
            """
            // Auto-generated by kotlin-native-export plugin. Do not modify.
            package demo

            enum class Empty {
            }

            """.trimIndent(),
            source,
        )
    }

    private fun generate(enum: KneEnum): String {
        val module = KneModule(
            libName = "demo",
            packages = setOf("demo"),
            classes = emptyList(),
            dataClasses = emptyList(),
            enums = listOf(enum),
            functions = emptyList(),
        )
        return FfmProxyGenerator().generate(module, "demo").getValue("${enum.simpleName}.kt")
    }
}
