package dev.nucleusframework.nna.plugin.codegen

import dev.nucleusframework.nna.plugin.analysis.PsiSourceParser
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

class FfmProxyGeneratorValueTypeSourceTest {

    @get:Rule
    val tmp = TemporaryFolder()

    @Test
    fun `enum is emitted exactly as declared on native side`() {
        val files = generate(
            """
            package demo

            import kotlinx.cinterop.ExperimentalForeignApi
            import kotlin.math.abs

            /** Arithmetic operation. */
            enum class Operation(val symbol: String) {
                ADD("+") {
                    override fun apply(a: Int, b: Int) = a + b
                },
                SUBTRACT("-") {
                    override fun apply(a: Int, b: Int) = abs(a - b)
                };

                abstract fun apply(a: Int, b: Int): Int

                companion object {
                    fun fromSymbol(symbol: String): Operation? = entries.firstOrNull { it.symbol == symbol }
                }
            }
            """,
        )

        assertEquals(
            """
            // Auto-generated by kotlin-native-export plugin. Do not modify.
            package demo

            import kotlin.math.abs

            /** Arithmetic operation. */
            enum class Operation(val symbol: String) {
                ADD("+") {
                    override fun apply(a: Int, b: Int) = a + b
                },
                SUBTRACT("-") {
                    override fun apply(a: Int, b: Int) = abs(a - b)
                };

                abstract fun apply(a: Int, b: Int): Int

                companion object {
                    fun fromSymbol(symbol: String): Operation? = entries.firstOrNull { it.symbol == symbol }
                }
            }

            """.trimIndent(),
            files.getValue("Operation.kt"),
        )
    }

    @Test
    fun `data class keeps defaults and body members`() {
        val files = generate(
            """
            package demo

            data class BinaryPayload(val name: String = "blob", val data: ByteArray) {
                val size: Int get() = data.size

                override fun equals(other: Any?): Boolean = other is BinaryPayload && name == other.name && data.contentEquals(other.data)
                override fun hashCode(): Int = 31 * name.hashCode() + data.contentHashCode()
            }
            """,
        )

        assertEquals(
            """
            // Auto-generated by kotlin-native-export plugin. Do not modify.
            package demo

            data class BinaryPayload(val name: String = "blob", val data: ByteArray) {
                val size: Int get() = data.size

                override fun equals(other: Any?): Boolean = other is BinaryPayload && name == other.name && data.contentEquals(other.data)
                override fun hashCode(): Int = 31 * name.hashCode() + data.contentHashCode()
            }

            """.trimIndent(),
            files.getValue("BinaryPayload.kt"),
        )
    }

    @Test
    fun `nested enum is re-indented to top level`() {
        val files = generate(
            """
            package demo.other

            class Holder {
                enum class Mode {
                    ON,
                    OFF,
                }
            }
            """,
        )

        assertEquals(
            """
            // Auto-generated by kotlin-native-export plugin. Do not modify.
            package demo

            enum class Mode {
                ON,
                OFF,
            }

            """.trimIndent(),
            files.getValue("Mode.kt"),
        )
    }

    private fun generate(source: String): Map<String, String> {
        val file = tmp.newFile("Source.kt").apply { writeText(source.trimIndent()) }
        val module = PsiSourceParser().parse(listOf(file), "demo", emptyList())
        return FfmProxyGenerator().generate(module, "demo")
    }
}
